name: Tests

on: [ push, pull_request ]

jobs:
  tests:
    name: OS ${{ matrix.os }}, PHP ${{ matrix.php }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.3', '7.4', '8.0', '8.1' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit

  coverage:
    name: Code coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          coverage: xdebug

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Code coverage
        run: "bash <(curl -s https://codecov.io/bash)"
